- hosts: localhost
  tasks:
    - name: Testing Module
      authtype_info: 
        type: ALL
        webfile: ./webfiles/formatted/multiexternal.txt
      register: result

    - debug: var=result    