- hosts: localhost
  tasks:
    - name: Testing Module
      auth-type: 
        type: Basic
        webfile: ./webfiles/formatted/top500_formatted.txt
      register: result

    - debug: var=result    